version: '3.1'

services:

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/reis:/data"
    
  nsqlookupd:
    image: nsqio/nsq:v0.3.8
    command: >
      /nsqlookupd
      -broadcast-address localhost:4160
    ports:
      - 4160:4160
      - 4161:4161

  nsqd:
    image: nsqio/nsq:v0.3.8
    command: >
      /nsqd
      -broadcast-address localhost:4150
      -lookupd-tcp-address nsqlookupd:4160
    ports:
      - 4150:4150
      - 4151:4151
    depends_on:
      - nsqlookupd
  
  twittervote:
    image: hysii/go-twittervotes:1.0
    command: >
      go run /go/go-twittervotes/tiwittervotes